import 'package:flutter/material.dart' hide DialogRoute, OverlayRoute;

import 'package:auto_route/auto_route.dart';
import 'package:flutter_web_plugins/flutter_web_plugins.dart';
import 'package:forui/forui.dart';

import 'package:docs_snippets/example.dart';
import 'package:docs_snippets/main.gr.dart';

class Options {
  final List<Object> include;
  final Type? inline;

  const Options({this.include = const [], this.inline});
}

void main() {
  usePathUrlStrategy();
  runApp(ForuiSamples());
}

class ForuiSamples extends StatelessWidget {
  final _router = _AppRouter();

  @override
  Widget build(BuildContext context) => MaterialApp.router(
    title: 'Forui Samples',
    theme: ThemeData(colorScheme: ColorScheme.fromSeed(seedColor: Colors.white), useMaterial3: true),
    localizationsDelegates: FLocalizations.localizationsDelegates,
    supportedLocales: FLocalizations.supportedLocales,
    routerConfig: _router.config(),
  );
}

@RoutePage()
class EmptyPage extends Example {
  @override
  Widget example(BuildContext context) => const SizedBox();
}

@AutoRouterConfig()
class _AppRouter extends RootStackRouter {
  @override
  List<AutoRoute> get routes => [
    AutoRoute(page: EmptyRoute.page, initial: true),
    // Data
    AutoRoute(path: '/data/accordion/default', page: AccordionRoute.page),
    AutoRoute(path: '/data/accordion/max', page: MaxAccordionRoute.page),
    AutoRoute(path: '/data/avatar/default', page: AvatarRoute.page),
    AutoRoute(path: '/data/avatar/raw', page: AvatarRawRoute.page),
    AutoRoute(path: '/data/avatar/invalid', page: AvatarInvalidRoute.page),
    AutoRoute(path: '/data/badge/primary', page: BadgePrimaryRoute.page),
    AutoRoute(path: '/data/badge/secondary', page: BadgeSecondaryRoute.page),
    AutoRoute(path: '/data/badge/destructive', page: BadgeDestructiveRoute.page),
    AutoRoute(path: '/data/badge/outline', page: BadgeOutlineRoute.page),
    AutoRoute(path: '/data/calendar/default', page: CalendarRoute.page),
    AutoRoute(path: '/data/calendar/dates', page: DatesCalendarRoute.page),
    AutoRoute(path: '/data/calendar/unselectable', page: UnselectableCalendarRoute.page),
    AutoRoute(path: '/data/calendar/range', page: RangeCalendarRoute.page),
    AutoRoute(path: '/data/card/default', page: CardRoute.page),
    AutoRoute(path: '/data/item/default', page: ItemRoute.page),
    AutoRoute(path: '/data/item/disabled', page: ItemDisabledRoute.page),
    AutoRoute(path: '/data/item/untappable', page: ItemUntappableRoute.page),
    AutoRoute(path: '/data/item/subtitle', page: ItemSubtitleRoute.page),
    AutoRoute(path: '/data/item/details', page: ItemDetailsRoute.page),
    AutoRoute(path: '/data/item/destructive', page: ItemDestructiveRoute.page),
    AutoRoute(path: '/data/item-group/default', page: ItemGroupRoute.page),
    AutoRoute(path: '/data/item-group/indented', page: ItemGroupIndentedRoute.page),
    AutoRoute(path: '/data/item-group/full', page: ItemGroupFullRoute.page),
    AutoRoute(path: '/data/item-group/scrollable', page: ScrollableItemGroupRoute.page),
    AutoRoute(path: '/data/item-group/lazy', page: LazyItemGroupRoute.page),
    AutoRoute(path: '/data/item-group/merge', page: MergeItemGroupRoute.page),
    AutoRoute(path: '/data/line-calendar/default', page: LineCalendarRoute.page),

    // Feedback
    AutoRoute(path: '/feedback/alert/primary', page: AlertPrimaryRoute.page),
    AutoRoute(path: '/feedback/alert/destructive', page: AlertDestructiveRoute.page),
    AutoRoute(path: '/feedback/progress/default', page: ProgressRoute.page),
    AutoRoute(path: '/feedback/progress/determinate', page: DeterminateProgressRoute.page),
    AutoRoute(path: '/feedback/progress/circular', page: CircularProgressRoute.page),

    // Form
    AutoRoute(path: '/form/autocomplete/default', page: AutocompleteRoute.page),
    AutoRoute(path: '/form/autocomplete/detailed', page: DetailedAutocompleteRoute.page),
    AutoRoute(path: '/form/autocomplete/section', page: SectionAutocompleteRoute.page),
    AutoRoute(path: '/form/autocomplete/divider', page: DividerAutocompleteRoute.page),
    AutoRoute(path: '/form/autocomplete/async', page: AsyncAutocompleteRoute.page),
    AutoRoute(path: '/form/autocomplete/async-loading', page: AsyncLoadingAutocompleteRoute.page),
    AutoRoute(path: '/form/autocomplete/async-error', page: AsyncErrorAutocompleteRoute.page),
    AutoRoute(path: '/form/autocomplete/clearable', page: ClearableAutocompleteRoute.page),
    AutoRoute(path: '/form/autocomplete/popover-builder', page: PopoverBuilderAutocompleteRoute.page),
    AutoRoute(path: '/form/autocomplete/form', page: FormAutocompleteRoute.page),
    AutoRoute(path: '/form/button/sizes', page: ButtonSizesRoute.page),
    AutoRoute(path: '/form/button/primary', page: ButtonPrimaryRoute.page),
    AutoRoute(path: '/form/button/secondary', page: ButtonSecondaryRoute.page),
    AutoRoute(path: '/form/button/destructive', page: ButtonDestructiveRoute.page),
    AutoRoute(path: '/form/button/ghost', page: ButtonGhostRoute.page),
    AutoRoute(path: '/form/button/outline', page: ButtonOutlineRoute.page),
    AutoRoute(path: '/form/button/icon', page: ButtonIconRoute.page),
    AutoRoute(path: '/form/button/only-icon', page: ButtonOnlyIconRoute.page),
    AutoRoute(path: '/form/button/toggle', page: ButtonToggleRoute.page),
    AutoRoute(path: '/form/button/circular-progress', page: ButtonCircularProgressRoute.page),
    AutoRoute(path: '/form/checkbox/default', page: CheckboxRoute.page),
    AutoRoute(path: '/form/checkbox/leading-label', page: LeadingLabelCheckboxRoute.page),
    AutoRoute(path: '/form/checkbox/disabled', page: DisabledCheckboxRoute.page),
    AutoRoute(path: '/form/checkbox/error', page: ErrorCheckboxRoute.page),
    AutoRoute(path: '/form/checkbox/raw', page: RawCheckboxRoute.page),
    AutoRoute(path: '/form/checkbox/form', page: FormCheckboxRoute.page),
    AutoRoute(path: '/form/date-field/default', page: DateFieldRoute.page),
    AutoRoute(path: '/form/date-field/clearable', page: ClearableDateFieldRoute.page),
    AutoRoute(path: '/form/date-field/calendar', page: CalendarDateFieldRoute.page),
    AutoRoute(path: '/form/date-field/input', page: InputDateFieldRoute.page),
    AutoRoute(path: '/form/date-field/popover-builder', page: PopoverBuilderDateFieldRoute.page),
    AutoRoute(path: '/form/date-field/validator', page: ValidatorDateFieldRoute.page),
    AutoRoute(path: '/form/date-field/form', page: FormDateFieldRoute.page),
    AutoRoute(path: '/form/date-time-picker/default', page: DateTimePickerRoute.page),
    AutoRoute(path: '/form/date-time-picker/hour24', page: Hour24DateTimePickerRoute.page),
    AutoRoute(path: '/form/date-time-picker/interval', page: IntervalDateTimePickerRoute.page),
    AutoRoute(path: '/form/label/vertical', page: VerticalLabelRoute.page),
    AutoRoute(path: '/form/label/horizontal', page: HorizontalLabelRoute.page),
    AutoRoute(path: '/form/label/disabled', page: DisabledHorizontalLabelRoute.page),
    AutoRoute(path: '/form/label/error', page: ErrorHorizontalLabelRoute.page),
    AutoRoute(path: '/form/multi-select/default', page: MultiSelectRoute.page),
    AutoRoute(path: '/form/multi-select/detailed', page: DetailedMultiSelectRoute.page),
    AutoRoute(path: '/form/multi-select/section', page: SectionMultiSelectRoute.page),
    AutoRoute(path: '/form/multi-select/divider', page: DividerMultiSelectRoute.page),
    AutoRoute(path: '/form/multi-select/sync', page: SyncMultiSelectRoute.page),
    AutoRoute(path: '/form/multi-select/async', page: AsyncMultiSelectRoute.page),
    AutoRoute(path: '/form/multi-select/async-loading', page: AsyncLoadingMultiSelectRoute.page),
    AutoRoute(path: '/form/multi-select/async-error', page: AsyncErrorMultiSelectRoute.page),
    AutoRoute(path: '/form/multi-select/clearable', page: ClearableMultiSelectRoute.page),
    AutoRoute(path: '/form/multi-select/format', page: FormatMultiSelectRoute.page),
    AutoRoute(path: '/form/multi-select/min-max', page: MinMaxMultiSelectRoute.page),
    AutoRoute(path: '/form/multi-select/sorted', page: SortedMultiSelectRoute.page),
    AutoRoute(path: '/form/multi-select/popover-builder', page: PopoverBuilderMultiSelectRoute.page),
    AutoRoute(path: '/form/multi-select/form', page: FormMultiSelectRoute.page),
    AutoRoute(path: '/form/otp-field/default', page: OtpFieldRoute.page),
    AutoRoute(path: '/form/otp-field/divider', page: DividerOtpFieldRoute.page),
    AutoRoute(path: '/form/otp-field/no-formatter', page: NoFormatterOtpFieldRoute.page),
    AutoRoute(path: '/form/picker/default', page: PickerRoute.page),
    AutoRoute(path: '/form/picker/loop', page: LoopPickerRoute.page),
    AutoRoute(path: '/form/picker/builder', page: BuilderPickerRoute.page),
    AutoRoute(path: '/form/picker/multiple', page: MultiPickerRoute.page),
    AutoRoute(path: '/form/picker/separator', page: SeparatedPickerRoute.page),
    AutoRoute(path: '/form/radio/default', page: RadioRoute.page),
    AutoRoute(path: '/form/radio/leading-label', page: LeadingLabelRadioRoute.page),
    AutoRoute(path: '/form/select/default', page: SelectRoute.page),
    AutoRoute(path: '/form/select/detailed', page: DetailedSelectRoute.page),
    AutoRoute(path: '/form/select/section', page: SectionSelectRoute.page),
    AutoRoute(path: '/form/select/divider', page: DividerSelectRoute.page),
    AutoRoute(path: '/form/select/sync', page: SyncSelectRoute.page),
    AutoRoute(path: '/form/select/async', page: AsyncSelectRoute.page),
    AutoRoute(path: '/form/select/async-loading', page: AsyncLoadingSelectRoute.page),
    AutoRoute(path: '/form/select/async-error', page: AsyncErrorSelectRoute.page),
    AutoRoute(path: '/form/select/toggleable', page: ToggleableSelectRoute.page),
    AutoRoute(path: '/form/select/clearable', page: ClearableSelectRoute.page),
    AutoRoute(path: '/form/select/popover-builder', page: PopoverBuilderSelectRoute.page),
    AutoRoute(path: '/form/select/format', page: FormatSelectRoute.page),
    AutoRoute(path: '/form/select/form', page: FormSelectRoute.page),
    AutoRoute(path: '/form/select-group/default', page: SelectGroupRoute.page),
    AutoRoute(path: '/form/select-group/checkbox-form', page: SelectGroupCheckboxFormRoute.page),
    AutoRoute(path: '/form/select-group/radio-form', page: SelectGroupRadioFormRoute.page),
    AutoRoute(path: '/form/slider/default', page: SliderRoute.page),
    AutoRoute(path: '/form/slider/labelled', page: LabelledSliderRoute.page),
    AutoRoute(path: '/form/slider/disabled', page: DisabledSliderRoute.page),
    AutoRoute(path: '/form/slider/error', page: ErrorSliderRoute.page),
    AutoRoute(path: '/form/slider/slide', page: SlideSliderRoute.page),
    AutoRoute(path: '/form/slider/slide-thumb', page: SlideThumbSliderRoute.page),
    AutoRoute(path: '/form/slider/tap', page: TapSliderRoute.page),
    AutoRoute(path: '/form/slider/tap-and-slide-thumb', page: TapAndSlideThumbSliderRoute.page),
    AutoRoute(path: '/form/slider/tooltip', page: TooltipSliderRoute.page),
    AutoRoute(path: '/form/slider/marks', page: MarksSliderRoute.page),
    AutoRoute(path: '/form/slider/discrete', page: DiscreteSliderRoute.page),
    AutoRoute(path: '/form/slider/range', page: RangeSliderRoute.page),
    AutoRoute(path: '/form/slider/boundaries', page: BoundariesSliderRoute.page),
    AutoRoute(path: '/form/slider/vertical', page: VerticalSliderRoute.page),
    AutoRoute(path: '/form/slider/form', page: SliderFormRoute.page),
    AutoRoute(path: '/form/switch/default', page: SwitchRoute.page),
    AutoRoute(path: '/form/switch/leading-label', page: LeadingLabelSwitchRoute.page),
    AutoRoute(path: '/form/switch/disabled', page: DisabledSwitchRoute.page),
    AutoRoute(path: '/form/switch/form', page: FormSwitchRoute.page),
    AutoRoute(path: '/form/text-field/default', page: TextFieldRoute.page),
    AutoRoute(path: '/form/text-field/disabled', page: DisabledTextFieldRoute.page),
    AutoRoute(path: '/form/text-field/clearable', page: ClearableTextFieldRoute.page),
    AutoRoute(path: '/form/text-field/email', page: EmailTextFieldRoute.page),
    AutoRoute(path: '/form/text-field/password', page: PasswordTextFieldRoute.page),
    AutoRoute(path: '/form/text-field/multiline', page: MultilineTextFieldRoute.page),
    AutoRoute(path: '/form/text-form-field/default', page: TextFormFieldRoute.page),
    AutoRoute(path: '/form/time-field/default', page: TimeFieldRoute.page),
    AutoRoute(path: '/form/time-field/hour24', page: Hour24TimeFieldRoute.page),
    AutoRoute(path: '/form/time-field/picker', page: PickerTimeFieldRoute.page),
    AutoRoute(path: '/form/time-field/popover-builder', page: PopoverBuilderTimeFieldRoute.page),
    AutoRoute(path: '/form/time-field/validator', page: ValidatorTimeFieldRoute.page),
    AutoRoute(path: '/form/time-field/form', page: FormTimeFieldRoute.page),
    AutoRoute(path: '/form/time-picker/default', page: TimePickerRoute.page),
    AutoRoute(path: '/form/time-picker/hour24', page: Hour24TimePickerRoute.page),
    AutoRoute(path: '/form/time-picker/interval', page: IntervalTimePickerRoute.page),
    AutoRoute(path: '/form/time-picker/animated', page: AnimatedTimePickerRoute.page),

    // Foundation
    AutoRoute(path: '/foundation/collapsible/default', page: CollapsibleRoute.page),
    AutoRoute(path: '/foundation/focused-outline/default', page: FocusedOutlineRoute.page),
    AutoRoute(path: '/foundation/overlay/default', page: OverlayRoute.page),
    AutoRoute(path: '/foundation/point-portal/default', page: PointPortalRoute.page),
    AutoRoute(path: '/foundation/portal/default', page: PortalRoute.page),
    AutoRoute(path: '/foundation/portal-visualization/default', page: PortalVisualizationRoute.page),
    AutoRoute(path: '/foundation/tappable/default', page: TappableRoute.page),
    AutoRoute(path: '/foundation/tappable/bounce', page: TappableBounceRoute.page),
    AutoRoute(path: '/foundation/tappable-group/default', page: TappableGroupRoute.page),

    // Layout
    AutoRoute(path: '/layout/divider/default', page: DividerRoute.page),
    AutoRoute(path: '/layout/resizable/default', page: ResizableRoute.page),
    AutoRoute(path: '/layout/resizable/no-cascading', page: NoCascadingResizableRoute.page),
    AutoRoute(path: '/layout/resizable/horizontal', page: HorizontalResizableRoute.page),
    AutoRoute(path: '/layout/resizable/divider', page: DividerResizableRoute.page),
    AutoRoute(path: '/layout/resizable/no-divider', page: NoDividerResizableRoute.page),
    AutoRoute(path: '/layout/scaffold/default', page: ScaffoldRoute.page),

    // Navigation
    AutoRoute(path: '/navigation/bottom-navigation-bar/default', page: BottomNavigationBarRoute.page),
    AutoRoute(path: '/navigation/breadcrumb/default', page: BreadcrumbRoute.page),
    AutoRoute(path: '/navigation/breadcrumb/tiles', page: BreadcrumbTilesRoute.page),
    AutoRoute(path: '/navigation/breadcrumb/divider', page: BreadcrumbDividerRoute.page),
    AutoRoute(path: '/navigation/header/default', page: RootHeaderRoute.page),
    AutoRoute(path: '/navigation/header/nested', page: NestedHeaderRoute.page),
    AutoRoute(path: '/navigation/header/nested-x', page: XNestedHeaderRoute.page),
    AutoRoute(path: '/navigation/pagination/default', page: PaginationRoute.page),
    AutoRoute(path: '/navigation/pagination/siblings', page: SiblingsPaginationRoute.page),
    AutoRoute(path: '/navigation/pagination/hide-edges', page: HideEdgesPaginationRoute.page),
    AutoRoute(path: '/navigation/pagination/custom-icon', page: PaginationCustomIconRoute.page),
    AutoRoute(path: '/navigation/pagination/page-view', page: PaginationWithViewRoute.page),
    AutoRoute(path: '/navigation/sidebar/default', page: SidebarRoute.page),
    AutoRoute(path: '/navigation/sidebar/sheet', page: SheetSidebarRoute.page),
    AutoRoute(path: '/navigation/sidebar/custom-width', page: CustomWidthSidebarRoute.page),
    AutoRoute(path: '/navigation/sidebar/nested', page: NestedSidebarRoute.page),
    AutoRoute(path: '/navigation/tabs/default', page: TabsRoute.page),
    AutoRoute(path: '/navigation/tabs/swipeable', page: SwipeableTabsRoute.page),

    // Overlay
    AutoRoute(path: '/overlay/context-menu/default', page: ContextMenuRoute.page),
    AutoRoute(path: '/overlay/context-menu/nested', page: NestedContextMenuRoute.page),
    AutoRoute(path: '/overlay/context-menu/tiles', page: TileContextMenuRoute.page),
    AutoRoute(path: '/overlay/dialog/default', page: DialogRoute.page),
    AutoRoute(path: '/overlay/dialog/vertical', page: VerticalDialogRoute.page),
    AutoRoute(path: '/overlay/dialog/blurred', page: BlurredDialogRoute.page),
    AutoRoute(path: '/overlay/modal-sheet/default', page: ModalSheetRoute.page),
    AutoRoute(path: '/overlay/modal-sheet/blurred', page: BlurredModalSheetRoute.page),
    AutoRoute(path: '/overlay/modal-sheet/draggable', page: DraggableModalSheetRoute.page),
    AutoRoute(path: '/overlay/persistent-sheet/default', page: PersistentSheetRoute.page),
    AutoRoute(path: '/overlay/persistent-sheet/keep-alive-offstage', page: KeepAliveOffstagePersistentSheetRoute.page),
    AutoRoute(path: '/overlay/persistent-sheet/draggable', page: DraggablePersistentSheetRoute.page),
    AutoRoute(path: '/overlay/popover/default', page: PopoverRoute.page),
    AutoRoute(path: '/overlay/popover/horizontal', page: HorizontalPopoverRoute.page),
    AutoRoute(path: '/overlay/popover/no-hide-region', page: NoHideRegionPopoverRoute.page),
    AutoRoute(path: '/overlay/popover/blurred', page: BlurredPopoverRoute.page),
    AutoRoute(path: '/overlay/popover/nested', page: NestedPopoverRoute.page),
    AutoRoute(path: '/overlay/popover/flip', page: FlipPopoverRoute.page),
    AutoRoute(path: '/overlay/popover/slide', page: SlidePopoverRoute.page),
    AutoRoute(path: '/overlay/popover/allow-overflow', page: AllowOverflowPopoverRoute.page),
    AutoRoute(path: '/overlay/popover-menu/default', page: PopoverMenuRoute.page),
    AutoRoute(path: '/overlay/popover-menu/blurred', page: BlurredPopoverMenuRoute.page),
    AutoRoute(path: '/overlay/popover-menu/nested', page: NestedPopoverMenuRoute.page),
    AutoRoute(path: '/overlay/popover-menu/tiles', page: TilePopoverMenuRoute.page),
    AutoRoute(path: '/overlay/toast/default', page: ToastRoute.page),
    AutoRoute(path: '/overlay/toast/destructive', page: DestructiveToastRoute.page),
    AutoRoute(path: '/overlay/toast/custom-alignment', page: CustomAlignmentToastRoute.page),
    AutoRoute(path: '/overlay/toast/no-auto-dismiss', page: NoAutoDismissToastRoute.page),
    AutoRoute(path: '/overlay/toast/raw', page: RawToastRoute.page),
    AutoRoute(path: '/overlay/toast/always-expand', page: AlwaysExpandToastRoute.page),
    AutoRoute(path: '/overlay/toast/disabled-expand', page: DisabledExpandToastRoute.page),
    AutoRoute(path: '/overlay/toast/swipe', page: SwipeToastRoute.page),
    AutoRoute(path: '/overlay/toast/swipe-down', page: DownSwipeToastRoute.page),
    AutoRoute(path: '/overlay/toast/swipe-disabled', page: DisabledSwipeToastRoute.page),
    AutoRoute(path: '/overlay/tooltip/default', page: TooltipRoute.page),
    AutoRoute(path: '/overlay/tooltip/horizontal', page: HorizontalTooltipRoute.page),
    AutoRoute(path: '/overlay/tooltip/long-press-only', page: LongPressOnlyTooltipRoute.page),
    AutoRoute(path: '/overlay/tooltip/group', page: GroupTooltipRoute.page),

    // Tile
    AutoRoute(path: '/tile/select-menu-tile/default', page: SelectMenuTileRoute.page),
    AutoRoute(path: '/tile/select-menu-tile/no-auto-hide', page: NoAutoHideSelectMenuTileRoute.page),
    AutoRoute(path: '/tile/select-menu-tile/scrollable', page: ScrollableSelectMenuTileRoute.page),
    AutoRoute(path: '/tile/select-menu-tile/lazy', page: LazySelectMenuTileRoute.page),
    AutoRoute(path: '/tile/select-menu-tile/form', page: SelectMenuTileFormRoute.page),
    AutoRoute(path: '/tile/select-tile-group/default', page: SelectTileGroupRoute.page),
    AutoRoute(path: '/tile/select-tile-group/full-divider', page: FullDividerSelectTileGroupRoute.page),
    AutoRoute(path: '/tile/select-tile-group/no-divider', page: NoDividerSelectTileGroupRoute.page),
    AutoRoute(path: '/tile/select-tile-group/scrollable', page: ScrollableSelectTileGroupRoute.page),
    AutoRoute(path: '/tile/select-tile-group/lazy', page: LazySelectTileGroupRoute.page),
    AutoRoute(path: '/tile/select-tile-group/multi-value', page: SelectTileGroupMultiValueRoute.page),
    AutoRoute(path: '/tile/select-tile-group/radio', page: SelectTileGroupRadioRoute.page),
    AutoRoute(path: '/tile/select-tile-group/suffix', page: SelectTileGroupSuffixRoute.page),
    AutoRoute(path: '/tile/tile/default', page: TileRoute.page),
    AutoRoute(path: '/tile/tile/destructive', page: TileDestructiveRoute.page),
    AutoRoute(path: '/tile/tile/disabled', page: DisabledTileRoute.page),
    AutoRoute(path: '/tile/tile/untappable', page: UntappableTileRoute.page),
    AutoRoute(path: '/tile/tile/subtitle', page: TileSubtitleRoute.page),
    AutoRoute(path: '/tile/tile/details', page: TileDetailsRoute.page),
    AutoRoute(path: '/tile/tile-group/default', page: TileGroupRoute.page),
    AutoRoute(path: '/tile/tile-group/scrollable', page: ScrollableTileGroupRoute.page),
    AutoRoute(path: '/tile/tile-group/lazy', page: LazyTileGroupRoute.page),
    AutoRoute(path: '/tile/tile-group/merge', page: MergeTileGroupRoute.page),
    AutoRoute(path: '/tile/tile-group/full-divider', page: FullDividerTileGroupRoute.page),
    AutoRoute(path: '/tile/tile-group/no-divider', page: NoDividerTileGroupRoute.page),
  ];
}
