// Copyright 2025 The Flutter Authors.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'dart:io';

import 'package:glob/glob.dart';
import 'package:logging/logging.dart';
import 'package:yaml/yaml.dart';

class PackagePolicy {
  const PackagePolicy({this.enabled = true, this.threshold});

  final bool enabled;
  final double? threshold;

  factory PackagePolicy.fromYaml(Object? yaml) {
    if (yaml is! YamlMap) {
      return const PackagePolicy();
    }
    final bool enabled = yaml['enabled'] as bool? ?? true;
    final thresholdNum = yaml['threshold'] as num?;
    return PackagePolicy(enabled: enabled, threshold: thresholdNum?.toDouble());
  }
}

class CoveragePolicy {
  CoveragePolicy({
    this.defaultThreshold = 80.0,
    this.enforceNoRegression = true,
    this.baselineFile = 'coverage_baseline.yaml',
    List<String> excludePatterns = const [],
    this.packages = const {},
  }) : excludeGlobs = excludePatterns.map(Glob.new).toList();

  final double defaultThreshold;
  final bool enforceNoRegression;
  final String baselineFile;
  final List<Glob> excludeGlobs;
  final Map<String, PackagePolicy> packages;

  static final Logger _log = Logger('CoveragePolicy');

  static CoveragePolicy load(File file) {
    if (!file.existsSync()) {
      return CoveragePolicy();
    }

    try {
      final String content = file.readAsStringSync();
      final Object? yaml = loadYaml(content);
      if (yaml is! YamlMap) {
        return CoveragePolicy();
      }

      final double defaultThreshold =
          (yaml['default_threshold'] as num? ?? 80.0).toDouble();
      final bool enforceNoRegression =
          yaml['enforce_no_regression'] as bool? ?? true;
      final String baselineFile =
          yaml['baseline_file'] as String? ?? 'coverage_baseline.yaml';

      final excludeRaw = yaml['exclude'] as YamlList?;
      final List<String> excludePatterns =
          excludeRaw?.map((e) => e.toString()).toList() ?? <String>[];

      final packagesRaw = yaml['packages'] as YamlMap?;
      final packages = <String, PackagePolicy>{};
      if (packagesRaw != null) {
        for (final MapEntry<dynamic, dynamic> entry in packagesRaw.entries) {
          packages[entry.key.toString()] = PackagePolicy.fromYaml(entry.value);
        }
      }

      return CoveragePolicy(
        defaultThreshold: defaultThreshold,
        enforceNoRegression: enforceNoRegression,
        baselineFile: baselineFile,
        excludePatterns: excludePatterns,
        packages: packages,
      );
    } catch (e) {
      _log.warning(
        'Failed to load coverage policy file: $e. Using default policy.',
      );
      return CoveragePolicy();
    }
  }

  bool isFileExcluded(String relativePath) {
    for (final Glob glob in excludeGlobs) {
      if (glob.matches(relativePath)) {
        return true;
      }
    }
    return false;
  }

  PackagePolicy getPackagePolicy(String relativePackageDir) {
    return packages[relativePackageDir] ?? const PackagePolicy();
  }
}

class CoverageBaseline {
  CoverageBaseline(this.highWaterMarks);

  final Map<String, double> highWaterMarks;

  static CoverageBaseline load(File file) {
    if (!file.existsSync()) {
      return CoverageBaseline({});
    }
    final String content = file.readAsStringSync();
    final Object? yaml = loadYaml(content);
    if (yaml is! YamlMap) {
      return CoverageBaseline({});
    }

    final marks = <String, double>{};
    for (final MapEntry<dynamic, dynamic> entry in yaml.entries) {
      final valueNum = entry.value as num?;
      if (valueNum != null) {
        marks[entry.key.toString()] = valueNum.toDouble();
      }
    }

    return CoverageBaseline(marks);
  }

  void save(File file) {
    final buffer = StringBuffer();
    buffer.writeln(
      '# Monorepo Coverage High-Water Marks (Auto-generated by test_and_fix '
      '--update-baseline)',
    );

    final List<String> sortedKeys = highWaterMarks.keys.toList()..sort();
    for (final key in sortedKeys) {
      buffer.writeln('$key: ${highWaterMarks[key]!.toStringAsFixed(2)}');
    }

    file.writeAsStringSync(buffer.toString());
  }
}
