// ignore_for_file: avoid_dynamic_calls

import 'dart:convert';
import 'dart:io';

final List<(String locale, String message)> locales = [
  ('af', 'Vandag'),
  ('am', 'ዛሬ'),
  ('ar', 'اليوم'),
  ('as', 'আজি'),
  ('az', 'Bu gün'),
  ('be', 'Сёння'),
  ('bg', 'Днес'),
  ('bn', 'আজ'),
  ('bs', 'Danas'),
  ('ca', 'Avui'),
  ('cs', 'Dnes'),
  ('cy', 'Heddiw'),
  ('da', 'I dag'),
  ('de', 'Heute'),
  ('de_CH', 'Heute'),
  ('el', 'Σήμερα'),
  ('en', 'Today'),
  ('en_AU', 'Today'),
  ('en_CA', 'Today'),
  ('en_GB', 'Today'),
  ('en_IE', 'Today'),
  ('en_IN', 'Today'),
  ('en_NZ', 'Today'),
  ('en_SG', 'Today'),
  ('en_ZA', 'Today'),
  ('es', 'Hoy'),
  ('es_419', 'Hoy'),
  ('es_AR', 'Hoy'),
  ('es_BO', 'Hoy'),
  ('es_CL', 'Hoy'),
  ('es_CO', 'Hoy'),
  ('es_CR', 'Hoy'),
  ('es_DO', 'Hoy'),
  ('es_EC', 'Hoy'),
  ('es_GT', 'Hoy'),
  ('es_HN', 'Hoy'),
  ('es_MX', 'Hoy'),
  ('es_NI', 'Hoy'),
  ('es_PA', 'Hoy'),
  ('es_PE', 'Hoy'),
  ('es_PR', 'Hoy'),
  ('es_PY', 'Hoy'),
  ('es_SV', 'Hoy'),
  ('es_US', 'Hoy'),
  ('es_UY', 'Hoy'),
  ('es_VE', 'Hoy'),
  ('et', 'Täna'),
  ('eu', 'Gaur'),
  ('fa', 'امروز'),
  ('fi', 'Tänään'),
  ('fil', 'Ngayon'),
  ('fr', "Aujourd'hui"),
  ('fr_CA', "Aujourd'hui"),
  ('gl', 'Hoxe'),
  ('gsw', 'Hüt'),
  ('gu', 'આજે'),
  ('he', 'היום'),
  ('hi', 'आज'),
  ('hr', 'Danas'),
  ('hu', 'Ma'),
  ('hy', 'Այսօր'),
  ('id', 'Hari ini'),
  ('is', 'Í dag'),
  ('it', 'Oggi'),
  ('ja', '今日'),
  ('ka', 'დღეს'),
  ('kk', 'Бүгін'),
  ('km', 'ថ្ងៃនេះ'),
  ('kn', 'ಇಂದು'),
  ('ko', '오늘'),
  ('ky', 'Бүгүн'),
  ('lo', 'ມື້ນີ້'),
  ('lt', 'Šiandien'),
  ('lv', 'Šodien'),
  ('mk', 'Денес'),
  ('ml', 'ഇന്ന്'),
  ('mn', 'Өнөөдөр'),
  ('mr', 'आज'),
  ('ms', 'Hari ini'),
  ('my', 'ယနေ့'),
  ('nb', 'I dag'),
  ('ne', 'आज'),
  ('nl', 'Vandaag'),
  ('no', 'I dag'),
  ('or', 'ଆଜି'),
  ('pa', 'ਅੱਜ'),
  ('pl', 'Dziś'),
  ('ps', 'نن'),
  ('pt', 'Hoje'),
  ('pt_PT', 'Hoje'),
  ('ro', 'Astăzi'),
  ('ru', 'Сегодня'),
  ('si', 'අද'),
  ('sk', 'Dnes'),
  ('sl', 'Danes'),
  ('sq', 'Sot'),
  ('sr', 'Данас'),
  ('sr_Latn', 'Danas'),
  ('sv', 'Idag'),
  ('sw', 'Leo'),
  ('ta', 'இன்று'),
  ('te', 'ఈ రోజు'),
  ('th', 'วันนี้'),
  ('tl', 'Ngayon'),
  ('tr', 'Bugün'),
  ('uk', 'Сьогодні'),
  ('ur', 'آج'),
  ('uz', 'Bugun'),
  ('vi', 'Hôm nay'),
  ('zh', '今天'),
  ('zh_HK', '今天'),
  ('zh_TW', '今天'),
  ('zu', 'Namuhla'),
];

void main() {
  // Replace with name of key to generate.
  const key = 'dateTimePickerToday';

  for (final (locale, value) in locales) {
    final arb = File('lib/l10n/f_$locale.arb');
    if (locale == 'en') {
      continue;
    }

    final data = json.decode(arb.readAsStringSync());
    data[key] = value;

    arb.writeAsStringSync(const JsonEncoder.withIndent('  ').convert(data));
  }
}
