import 'package:analyzer/dart/analysis/analysis_context_collection.dart';
import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/ast/visitor.dart';
import 'package:code_builder/code_builder.dart';
import 'package:path/path.dart' as p;
import 'package:sugar/sugar.dart';

import 'constructors.dart';
import 'main.dart';

typedef ThemesConstructors = ({
  Map<String, ConstructorMatch> typography,
  Map<String, ConstructorMatch> style,
  Map<String, String> icons,
  Map<(String, String?), List<ThemeConstructor>> themes,
});

typedef ThemeConstructor = ({String theme, String variant, String colors});

typedef ThemeFragment = ({String theme, String colors, String typography, String style});

final _colors = p.join(library, 'src', 'theme', 'colors.dart');
final _icons = p.join(library, 'src', 'theme', 'icons.dart');
final _themes = p.join(library, 'src', 'theme', 'themes.dart');

final _typography = RegExp('FTypography');
final _typographyConstructor = RegExp(r'(FTypography)\.inherit');
final _style = RegExp(r'^FStyle$');
final _styleConstructor = RegExp(r'(FStyle)\.inherit');

String generateThemes(Map<(String, String?), ThemeFragment> fragments) {
  final registry = LibraryBuilder()
    ..comments.addAll([header])
    ..body.addAll([
      (EnumBuilder()
            ..docs.addAll(['/// All themes in Forui. Generated by tool/cli_generator.'])
            ..name = 'Theme'
            ..values.addAll([
              for (final MapEntry(key: (theme, variant), value: fragment) in fragments.entries)
                (EnumValueBuilder()
                      ..name = '$theme${variant == null ? '' : variant.capitalize()}'
                      ..arguments.addAll([
                        literalString('$theme${variant == null ? '' : '-$variant'}'),
                        literalString(fragment.theme.replaceAll(r'$', r'\$')),
                        literalString(fragment.colors.replaceAll(r'$', r'\$')),
                        literalString(fragment.typography.replaceAll(r'$', r'\$')),
                        literalString(fragment.style.replaceAll(r'$', r'\$')),
                      ]))
                    .build(),
            ])
            ..fields.addAll([
              (FieldBuilder()
                    ..docs.addAll(['/// The name.'])
                    ..name = 'name'
                    ..type = refer('String')
                    ..modifier = FieldModifier.final$)
                  .build(),
              (FieldBuilder()
                    ..docs.addAll(['/// The theme.dart source.'])
                    ..name = 'source'
                    ..type = refer('String')
                    ..modifier = FieldModifier.final$)
                  .build(),
              (FieldBuilder()
                    ..docs.addAll(['/// The colors.dart source.'])
                    ..name = 'colors'
                    ..type = refer('String')
                    ..modifier = FieldModifier.final$)
                  .build(),
              (FieldBuilder()
                    ..docs.addAll(['/// The typography.dart source.'])
                    ..name = 'typography'
                    ..type = refer('String')
                    ..modifier = FieldModifier.final$)
                  .build(),
              (FieldBuilder()
                    ..docs.addAll(['/// The style.dart source.'])
                    ..name = 'style'
                    ..type = refer('String')
                    ..modifier = FieldModifier.final$)
                  .build(),
            ])
            ..constructors.add(
              (ConstructorBuilder()
                    ..constant = true
                    ..requiredParameters.addAll([
                      Parameter((p) => p..name = 'this.name'),
                      Parameter((p) => p..name = 'this.source'),
                      Parameter((p) => p..name = 'this.colors'),
                      Parameter((p) => p..name = 'this.typography'),
                      Parameter((p) => p..name = 'this.style'),
                    ]))
                  .build(),
            ))
          .build(),
    ]);

  return metaFormatter.format(registry.build().accept(emitter).toString());
}

Map<(String, String?), ThemeFragment> mapThemes(ThemesConstructors themes) {
  final typography = ConstructorFragment.inline(_typographyConstructor, themes.typography).values.single;
  final icons = StringBuffer('FIcons(\n');
  for (final MapEntry(:key, :value) in themes.icons.entries) {
    icons.writeln('  $key: $value,');
  }
  icons.writeln(');');
  final style = ConstructorFragment.inline(_styleConstructor, themes.style).values.single;

  final fragments = <(String, String?), ThemeFragment>{};
  for (final MapEntry(:key, value: constructors) in themes.themes.entries) {
    final themeBuffer = StringBuffer();
    final colorsBuffer = StringBuffer();
    final typographyBuffer = StringBuffer();
    final styleBuffer = StringBuffer();

    for (final constructor in constructors) {
      final name = '${constructor.theme}${constructor.variant.capitalize()}';
      final colors = '${constructor.variant}Colors';

      themeBuffer.writeln('''
        FThemeData get $name {
          // Change this to false to use the desktop variant of this theme.
          const touch = true;
          
          final colors = $colors;
          
          final typography = _typography(colors: colors, touch: touch);
          
          final icons = $icons
          
          final style = _style(colors: colors, typography: typography, touch: touch);

          return FThemeData(
            colors: colors,
            typography: typography,
            icons: icons,
            style: style,
            touch: touch,
          );
        }

        ''');

      colorsBuffer
        ..writeln(
          'final FColors $colors = ${constructor.colors.replaceFirst(RegExp(r',?\s*\)\s*$'), ', extensions: const [AppColors()])')};',
        )
        ..writeln();
    }

    colorsBuffer.writeln('''
/// Provides convenient access to theme extensions on [FColors].
///
/// ```dart
/// final accent = context.theme.colors.app.accent; ✅
///
/// // Alternatively, you can create a getter to access extension fields directly.
/// final accent = context.theme.colors.accent; ✅
///
/// final accent = context.theme.colors.extension<AppColors>().accent; ❌
/// ```
extension FColorsExtensions on FColors {
  AppColors get app => extension<AppColors>();
}

/// Custom color tokens unique to your app.
///
/// Add your fields below, then implement [copyWith], [lerp], [==], and [hashCode].
/// See https://api.flutter.dev/flutter/material/ThemeExtension-class.html.
class AppColors extends ThemeExtension<AppColors> {
  // TODO: add your color fields here:
  // final Color accent;

  const AppColors();

  @override
  AppColors copyWith() => const AppColors();

  @override
  AppColors lerp(covariant AppColors? other, double t) {
    if (other == null) {
      return this;
    }
    return const AppColors();
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is AppColors && runtimeType == other.runtimeType;

  @override
  int get hashCode => runtimeType.hashCode;
}
''');

    typographyBuffer
      ..write(typography.source.substring(0, typography.type.length + 1))
      ..write('_')
      ..writeln(
        typography.source
            .substring(typography.type.length + 1)
            .replaceAll('extensions: const [],', 'extensions: const [AppTypography()],'),
      )
      ..writeln('''
/// Provides convenient access to theme extensions on [FTypography].
///
/// ```dart
/// final display = context.theme.typography.app.display; ✅
///
/// // Alternatively, you can create a getter to access extension fields directly.
/// final display = context.theme.typography.display; ✅
///
/// final display = context.theme.typography.extension<AppTypography>().display; ❌
/// ```
extension FTypographyExtensions on FTypography {
  AppTypography get app => extension<AppTypography>();
}

/// Custom typography tokens unique to your app.
///
/// Add your fields below, then implement [copyWith], [lerp], [scale], [==], and [hashCode].
/// See [FTypographyExtension].
class AppTypography extends FTypographyExtension<AppTypography> {
  // TODO: add your typography fields here:
  // final TextStyle display;

  const AppTypography();

  @override
  AppTypography copyWith() => const AppTypography();

  @override
  AppTypography lerp(covariant AppTypography? other, double t) {
    if (other == null) {
      return this;
    }
    return const AppTypography();
  }

  @override
  AppTypography scale({double sizeScalar = 1.0}) => this;

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is AppTypography && runtimeType == other.runtimeType;

  @override
  int get hashCode => runtimeType.hashCode;
}
''');

    styleBuffer
      ..write(style.source.substring(0, style.type.length + 1))
      ..write('_')
      ..writeln(
        style.source
            .substring(style.type.length + 1)
            .replaceAll('extensions: const [],', 'extensions: const [AppStyle()],'),
      )
      ..writeln('''
/// Provides convenient access to theme extensions on [FStyle].
///
/// ```dart
/// final cardRadius = context.theme.style.app.cardRadius; ✅
///
/// // Alternatively, you can create a getter to access extension fields directly.
/// final cardRadius = context.theme.style.cardRadius; ✅
///
/// final cardRadius = context.theme.style.extension<AppStyle>().cardRadius; ❌
/// ```
extension FStyleExtensions on FStyle {
  AppStyle get app => extension<AppStyle>();
}

/// Custom style tokens unique to your app.
///
/// Add your fields below, then implement [copyWith], [lerp], [==], and [hashCode].
/// See https://api.flutter.dev/flutter/material/ThemeExtension-class.html.
class AppStyle extends ThemeExtension<AppStyle> {
  // TODO: add your style fields here:
  // final double cardRadius;

  const AppStyle();

  @override
  AppStyle copyWith() => const AppStyle();

  @override
  AppStyle lerp(covariant AppStyle? other, double t) {
    if (other == null) {
      return this;
    }
    return const AppStyle();
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is AppStyle && runtimeType == other.runtimeType;

  @override
  int get hashCode => runtimeType.hashCode;
}
''');

    fragments[key] = (
      theme: fragmentFormatter.format(themeBuffer.toString()),
      colors: fragmentFormatter.format(colorsBuffer.toString()),
      typography: fragmentFormatter.format(typographyBuffer.toString()),
      style: fragmentFormatter.format(styleBuffer.toString()),
    );
  }

  return fragments;
}

/// Traverses the library and finds all themes.
Future<ThemesConstructors> traverseThemes(AnalysisContextCollection collection) async {
  final typography = await ConstructorMatch.traverse(collection, _typography, _typographyConstructor, {'FTypography'});
  final style = await ConstructorMatch.traverse(collection, _style, _styleConstructor, {'FStyle'});

  // Parse colors.dart to build a map from field name to inline FColors(...) expression.
  final colors = <String, String>{};
  if (await collection.contextFor(_colors).currentSession.getResolvedUnit(_colors)
      case final ResolvedUnitResult result) {
    final visitor = _ColorsVisitor();
    result.unit.accept(visitor);
    colors.addAll(visitor.colors);
  }

  // Parse icons.dart to build a map from FIcons field name to its FIcons.lucide() initializer expression.
  final icons = <String, String>{};
  if (await collection.contextFor(_icons).currentSession.getResolvedUnit(_icons) case final ResolvedUnitResult result) {
    final visitor = _IconsVisitor();
    result.unit.accept(visitor);
    icons.addAll(visitor.icons);
  }

  if (await collection.contextFor(_themes).currentSession.getResolvedUnit(_themes)
      case final ResolvedUnitResult result) {
    final visitor = _ThemesVisitor(colors);
    result.unit.accept(visitor);

    return (typography: typography, icons: icons, style: style, themes: visitor.themes);
  }

  throw Exception('Failed to parse $_colors & $_themes');
}

class _ColorsVisitor extends RecursiveAstVisitor<void> {
  final Map<String, String> colors = {};
  bool _inside = false;

  @override
  void visitClassDeclaration(ClassDeclaration declaration) {
    if (declaration.namePart.typeName.lexeme == 'FColors') {
      _inside = true;
      super.visitClassDeclaration(declaration);
      _inside = false;
    }
  }

  @override
  void visitFieldDeclaration(FieldDeclaration field) {
    if (!_inside || !field.isStatic) {
      return;
    }

    for (final variable in field.fields.variables) {
      if (variable.initializer != null) {
        colors[variable.name.lexeme] = variable.initializer!.toSource().replaceAll('FColors._', 'FColors');
      }
    }
  }
}

class _IconsVisitor extends RecursiveAstVisitor<void> {
  // Icon name -> default initializer expression (qualified, e.g. `FIcons.iconData(FLucideIcons.arrowLeft)`).
  final Map<String, String> icons = {};
  bool _inside = false;

  @override
  void visitClassDeclaration(ClassDeclaration declaration) {
    if (declaration.namePart.typeName.lexeme == 'FIcons') {
      _inside = true;
      super.visitClassDeclaration(declaration);
      _inside = false;
    }
  }

  @override
  void visitConstructorDeclaration(ConstructorDeclaration declaration) {
    if (_inside && declaration.name?.lexeme == 'lucide') {
      for (final initializer in declaration.initializers) {
        if (initializer case RedirectingConstructorInvocation(argumentList: ArgumentList(:final arguments))) {
          for (final NamedExpression(:name, :expression) in arguments.whereType<NamedExpression>()) {
            icons[name.label.name] = 'FIcons.${expression.toSource()}';
          }
        }
      }
    }
  }
}

class _ThemesVisitor extends RecursiveAstVisitor<void> {
  final Map<String, String> _colors;
  final Map<(String, String?), List<ThemeConstructor>> themes = {};

  _ThemesVisitor(this._colors);

  @override
  void visitFieldDeclaration(FieldDeclaration field) {
    if (!field.isStatic) {
      return;
    }

    for (final variable in field.fields.variables) {
      final theme = variable.name.lexeme;

      // Match (light: FPlatformThemeData(desktop: () => FThemeData(...), touch: () => FThemeData(...)), dark: ...)
      if (variable.initializer case final RecordLiteral autoTheme) {
        for (final NamedExpression(:name, :expression) in autoTheme.fields.whereType<NamedExpression>()) {
          final variant = name.label.name; // "light" or "dark"

          // FPlatformThemeData(desktop: () => FThemeData(...), touch: () => FThemeData(...))
          if (expression case final InstanceCreationExpression platformTheme) {
            // Extract colors from the touch variant
            for (final NamedExpression(:name, :expression)
                in platformTheme.argumentList.arguments.whereType<NamedExpression>()) {
              if (name.label.name != 'touch') {
                continue;
              }

              // () => FThemeData(colors: ...) — unwrap the closure
              final themeDataExpr = switch (expression) {
                FunctionExpression(body: ExpressionFunctionBody(:final expression)) => expression,
                _ => expression,
              };

              // FThemeData(colors: ...)
              if (themeDataExpr case final InstanceCreationExpression themeData) {
                var colors = '';
                for (final expression in themeData.argumentList.arguments.whereType<NamedExpression>()) {
                  if (expression.name.label.name == 'colors') {
                    final source = expression.expression.toSource();
                    // Resolve named constants (e.g. FColors.zincLight) to their inline definition.
                    colors = source.startsWith('FColors.')
                        ? (_colors[source.substring('FColors.'.length)] ?? source)
                        : source;
                  }
                }

                final constructor = (theme: theme, variant: variant, colors: colors);
                (themes[(theme, null)] ??= []).add(constructor);
                (themes[(theme, constructor.variant)] ??= []).add(constructor);
              }
            }
          }
        }
      }
    }
  }
}
