import 'package:flutter/gestures.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/widgets.dart';

import 'package:forui/forui.dart';
import 'package:forui/src/widgets/select_menu_tile.dart';

/// A marker interface which denotes that mixed-in widgets can be used in a [FTileGroup].
mixin FTileMixin on Widget {
  /// {@macro forui.widgets.FSelectMenuTile.new}
  ///
  /// This function is a shorthand for [FSelectMenuTile.new].
  static FSelectMenuTile<T> selectMenu<T>({
    required Widget title,
    required List<FSelectTile<T>> menu,
    FMultiValueControl<T>? selectControl,
    FPopoverControl popoverControl = const .managed(),
    ScrollController? scrollController,
    FSelectMenuTileStyleDelta style = const .context(),
    ScrollCacheExtent? scrollCacheExtent,
    double maxHeight = .infinity,
    DragStartBehavior dragStartBehavior = .start,
    ScrollPhysics physics = const ClampingScrollPhysics(),
    FItemDivider divider = .full,
    AlignmentGeometry menuAnchor = .topRight,
    AlignmentGeometry tileAnchor = .bottomRight,
    FPortalSpacing menuSpacing = const .spacing(4),
    FPortalOverflow menuOverflow = .flip,
    Offset menuOffset = .zero,
    FPopoverHideRegion menuHideRegion = .excludeChild,
    VoidCallback? menuOnTapHide,
    Object? menuGroupId,
    bool autoHide = true,
    Widget? label,
    Widget? description,
    bool autofocus = false,
    FocusScopeNode? menuFocusNode,
    ValueChanged<bool>? menuOnFocusChange,
    TraversalEdgeBehavior? menuTraversalEdgeBehavior,
    String? menuBarrierSemanticsLabel,
    bool menuBarrierSemanticsDismissible = true,
    String? semanticsLabel,
    Widget? prefix,
    Widget? subtitle,
    ValueWidgetBuilder<Set<T>> detailsBuilder = defaultSelectMenuTileBuilder,
    Widget? details,
    Widget? suffix,
    Map<ShortcutActivator, Intent>? shortcuts,
    Map<Type, Action<Intent>>? actions,
    Widget Function(BuildContext context, String message) errorBuilder = FFormFieldProperties.defaultErrorBuilder,
    FormFieldSetter<Set<T>>? onSaved,
    VoidCallback? onReset,
    FormFieldValidator<Set<T>>? validator,
    String? forceErrorText,
    bool enabled = true,
    AutovalidateMode autovalidateMode = .disabled,
    Key? key,
  }) => .new(
    title: title,
    menu: menu,
    selectControl: selectControl,
    popoverControl: popoverControl,
    scrollController: scrollController,
    style: style,
    scrollCacheExtent: scrollCacheExtent,
    maxHeight: maxHeight,
    dragStartBehavior: dragStartBehavior,
    physics: physics,
    divider: divider,
    menuAnchor: menuAnchor,
    tileAnchor: tileAnchor,
    menuSpacing: menuSpacing,
    menuOverflow: menuOverflow,
    menuOffset: menuOffset,
    menuHideRegion: menuHideRegion,
    menuOnTapHide: menuOnTapHide,
    menuGroupId: menuGroupId,
    autoHide: autoHide,
    label: label,
    description: description,
    autofocus: autofocus,
    menuFocusNode: menuFocusNode,
    menuOnFocusChange: menuOnFocusChange,
    menuTraversalEdgeBehavior: menuTraversalEdgeBehavior,
    menuBarrierSemanticsLabel: menuBarrierSemanticsLabel,
    menuBarrierSemanticsDismissible: menuBarrierSemanticsDismissible,
    semanticsLabel: semanticsLabel,
    prefix: prefix,
    subtitle: subtitle,
    detailsBuilder: detailsBuilder,
    details: details,
    suffix: suffix,
    shortcuts: shortcuts,
    actions: actions,
    errorBuilder: errorBuilder,
    onSaved: onSaved,
    onReset: onReset,
    validator: validator,
    forceErrorText: forceErrorText,
    enabled: enabled,
    autovalidateMode: autovalidateMode,
    key: key,
  );

  /// {@macro forui.widgets.FSelectMenuTile.fromMap}
  ///
  /// This function is a shorthand for [FSelectMenuTile.fromMap].
  static FSelectMenuTile<T> selectMenuFromMap<T>(
    Map<String, T> menu, {
    required Text title,
    FMultiValueControl<T>? selectControl,
    FPopoverControl popoverControl = const .managed(),
    ScrollController? scrollController,
    FSelectMenuTileStyleDelta style = const .context(),
    ScrollCacheExtent? scrollCacheExtent,
    double maxHeight = .infinity,
    DragStartBehavior dragStartBehavior = .start,
    ScrollPhysics physics = const ClampingScrollPhysics(),
    FItemDivider divider = .full,
    AlignmentGeometry menuAnchor = .topRight,
    AlignmentGeometry tileAnchor = .bottomRight,
    FPortalSpacing menuSpacing = const .spacing(4),
    FPortalOverflow menuOverflow = .flip,
    Offset menuOffset = .zero,
    FPopoverHideRegion menuHideRegion = .excludeChild,
    VoidCallback? menuOnTapHide,
    Object? menuGroupId,
    bool autoHide = true,
    Widget? label,
    Widget? description,
    bool autofocus = false,
    FocusScopeNode? menuFocusNode,
    ValueChanged<bool>? menuOnFocusChange,
    TraversalEdgeBehavior? menuTraversalEdgeBehavior,
    String? menuBarrierSemanticsLabel,
    bool menuBarrierSemanticsDismissible = true,
    String? semanticsLabel,
    Widget? prefix,
    Widget? subtitle,
    ValueWidgetBuilder<Set<T>> detailsBuilder = defaultSelectMenuTileBuilder,
    Widget? details,
    Widget? suffix,
    Map<ShortcutActivator, Intent>? shortcuts,
    Map<Type, Action<Intent>>? actions,
    Widget Function(BuildContext context, String message) errorBuilder = FFormFieldProperties.defaultErrorBuilder,
    FormFieldSetter<Set<T>>? onSaved,
    VoidCallback? onReset,
    FormFieldValidator<Set<T>>? validator,
    String? forceErrorText,
    bool enabled = true,
    AutovalidateMode autovalidateMode = .disabled,
    Key? key,
  }) => .fromMap(
    menu,
    title: title,
    selectControl: selectControl,
    popoverControl: popoverControl,
    scrollController: scrollController,
    style: style,
    scrollCacheExtent: scrollCacheExtent,
    maxHeight: maxHeight,
    dragStartBehavior: dragStartBehavior,
    physics: physics,
    divider: divider,
    menuAnchor: menuAnchor,
    tileAnchor: tileAnchor,
    menuSpacing: menuSpacing,
    menuOverflow: menuOverflow,
    menuOffset: menuOffset,
    menuHideRegion: menuHideRegion,
    menuOnTapHide: menuOnTapHide,
    menuGroupId: menuGroupId,
    autoHide: autoHide,
    label: label,
    description: description,
    autofocus: autofocus,
    menuFocusNode: menuFocusNode,
    menuOnFocusChange: menuOnFocusChange,
    menuTraversalEdgeBehavior: menuTraversalEdgeBehavior,
    menuBarrierSemanticsLabel: menuBarrierSemanticsLabel,
    menuBarrierSemanticsDismissible: menuBarrierSemanticsDismissible,
    semanticsLabel: semanticsLabel,
    prefix: prefix,
    subtitle: subtitle,
    detailsBuilder: detailsBuilder,
    details: details,
    suffix: suffix,
    shortcuts: shortcuts,
    actions: actions,
    errorBuilder: errorBuilder,
    onSaved: onSaved,
    onReset: onReset,
    validator: validator,
    forceErrorText: forceErrorText,
    enabled: enabled,
    autovalidateMode: autovalidateMode,
    key: key,
  );

  /// {@macro forui.widgets.FSelectMenuTile.builder}
  ///
  /// This function is a shorthand for [FSelectMenuTile.builder].
  static FSelectMenuTile<T> selectMenuBuilder<T>({
    required Widget title,
    required FSelectTile<T>? Function(BuildContext context, int index) menuBuilder,
    int? count,
    FMultiValueControl<T>? selectControl,
    FPopoverControl popoverControl = const .managed(),
    ScrollController? scrollController,
    FSelectMenuTileStyleDelta style = const .context(),
    ScrollCacheExtent? scrollCacheExtent,
    double maxHeight = .infinity,
    DragStartBehavior dragStartBehavior = .start,
    ScrollPhysics physics = const ClampingScrollPhysics(),
    FItemDivider divider = .full,
    AlignmentGeometry menuAnchor = .topRight,
    AlignmentGeometry tileAnchor = .bottomRight,
    FPortalSpacing menuSpacing = const .spacing(4),
    FPortalOverflow menuOverflow = .flip,
    Offset menuOffset = .zero,
    FPopoverHideRegion menuHideRegion = .excludeChild,
    VoidCallback? menuOnTapHide,
    Object? menuGroupId,
    bool autoHide = true,
    Widget? label,
    Widget? description,
    bool autofocus = false,
    FocusScopeNode? menuFocusNode,
    ValueChanged<bool>? menuOnFocusChange,
    TraversalEdgeBehavior? menuTraversalEdgeBehavior,
    String? menuBarrierSemanticsLabel,
    bool menuBarrierSemanticsDismissible = true,
    String? semanticsLabel,
    Widget? prefix,
    Widget? subtitle,
    ValueWidgetBuilder<Set<T>> detailsBuilder = defaultSelectMenuTileBuilder,
    Widget? details,
    Widget? suffix,
    Map<ShortcutActivator, Intent>? shortcuts,
    Map<Type, Action<Intent>>? actions,
    Widget Function(BuildContext context, String message) errorBuilder = FFormFieldProperties.defaultErrorBuilder,
    FormFieldSetter<Set<T>>? onSaved,
    VoidCallback? onReset,
    FormFieldValidator<Set<T>>? validator,
    String? forceErrorText,
    bool enabled = true,
    AutovalidateMode autovalidateMode = .disabled,
    Key? key,
  }) => .builder(
    title: title,
    menuBuilder: menuBuilder,
    count: count,
    selectControl: selectControl,
    popoverControl: popoverControl,
    scrollController: scrollController,
    style: style,
    scrollCacheExtent: scrollCacheExtent,
    maxHeight: maxHeight,
    dragStartBehavior: dragStartBehavior,
    physics: physics,
    divider: divider,
    menuAnchor: menuAnchor,
    tileAnchor: tileAnchor,
    menuSpacing: menuSpacing,
    menuOverflow: menuOverflow,
    menuOffset: menuOffset,
    menuHideRegion: menuHideRegion,
    menuOnTapHide: menuOnTapHide,
    menuGroupId: menuGroupId,
    autoHide: autoHide,
    label: label,
    description: description,
    autofocus: autofocus,
    menuFocusNode: menuFocusNode,
    menuOnFocusChange: menuOnFocusChange,
    menuTraversalEdgeBehavior: menuTraversalEdgeBehavior,
    menuBarrierSemanticsLabel: menuBarrierSemanticsLabel,
    menuBarrierSemanticsDismissible: menuBarrierSemanticsDismissible,
    semanticsLabel: semanticsLabel,
    prefix: prefix,
    subtitle: subtitle,
    detailsBuilder: detailsBuilder,
    details: details,
    suffix: suffix,
    shortcuts: shortcuts,
    actions: actions,
    errorBuilder: errorBuilder,
    onSaved: onSaved,
    onReset: onReset,
    validator: validator,
    forceErrorText: forceErrorText,
    enabled: enabled,
    autovalidateMode: autovalidateMode,
    key: key,
  );

  /// Creates a [FSubmenuTile].
  ///
  /// This function is a shorthand for [FSubmenuTile.new].
  static FSubmenuTile submenu({
    required Widget title,
    required List<FTileGroupMixin> menu,
    FPopoverControl control = const .managed(),
    FItemVariant variant = .primary,
    FItemStyleDelta style = const .context(),
    bool? enabled,
    String? semanticsLabel,
    bool autofocus = false,
    FocusNode? focusNode,
    ValueChanged<bool>? onFocusChange,
    FTappableVariantChangeCallback? onVariantChange,
    VoidCallback? onLongPress,
    VoidCallback? onDoubleTap,
    VoidCallback? onSecondaryPress,
    VoidCallback? onSecondaryLongPress,
    Map<ShortcutActivator, Intent>? shortcuts,
    Map<Type, Action<Intent>>? actions,
    Widget? prefix,
    Widget? subtitle,
    Widget? suffix,
    FPopoverMenuStyleDelta menuStyle = const .context(),
    AlignmentGeometry? menuAnchor,
    AlignmentGeometry? childAnchor,
    ScrollController? submenuScrollController,
    ScrollCacheExtent? submenuScrollCacheExtent,
    bool? submenuIntrinsicWidth,
    DragStartBehavior submenuDragStartBehavior = .start,
    FPortalSpacing submenuSpacing = const .spacing(2),
    FPortalOverflow submenuOverflow = .flip,
    Offset submenuOffset = .zero,
    FPopoverHideRegion submenuHideRegion = .excludeChild,
    String? submenuSemanticsLabel,
    bool submenuUseViewPadding = true,
    bool submenuUseViewInsets = true,
    bool? submenuAutofocus,
    FocusScopeNode? submenuFocusNode,
    ValueChanged<bool>? submenuOnFocusChange,
    TraversalEdgeBehavior? submenuTraversalEdgeBehavior,
    double submenuMaxHeight = .infinity,
    FItemDivider submenuDivider = .full,
    Key? key,
  }) => .new(
    title: title,
    menu: menu,
    control: control,
    variant: variant,
    style: style,
    enabled: enabled,
    semanticsLabel: semanticsLabel,
    autofocus: autofocus,
    focusNode: focusNode,
    onFocusChange: onFocusChange,
    onVariantChange: onVariantChange,
    onLongPress: onLongPress,
    onDoubleTap: onDoubleTap,
    onSecondaryPress: onSecondaryPress,
    onSecondaryLongPress: onSecondaryLongPress,
    shortcuts: shortcuts,
    actions: actions,
    prefix: prefix,
    subtitle: subtitle,
    suffix: suffix,
    menuStyle: menuStyle,
    menuAnchor: menuAnchor,
    childAnchor: childAnchor,
    submenuScrollController: submenuScrollController,
    submenuScrollCacheExtent: submenuScrollCacheExtent,
    submenuIntrinsicWidth: submenuIntrinsicWidth,
    submenuDragStartBehavior: submenuDragStartBehavior,
    submenuSpacing: submenuSpacing,
    submenuOverflow: submenuOverflow,
    submenuOffset: submenuOffset,
    submenuHideRegion: submenuHideRegion,
    submenuSemanticsLabel: submenuSemanticsLabel,
    submenuUseViewPadding: submenuUseViewPadding,
    submenuUseViewInsets: submenuUseViewInsets,
    submenuAutofocus: submenuAutofocus,
    submenuFocusNode: submenuFocusNode,
    submenuOnFocusChange: submenuOnFocusChange,
    submenuTraversalEdgeBehavior: submenuTraversalEdgeBehavior,
    submenuMaxHeight: submenuMaxHeight,
    submenuDivider: submenuDivider,
    key: key,
  );

  /// {@macro forui.widgets.FTile.new}
  ///
  /// This function is a shorthand for [FTile.new].
  static FTile tile({
    required Widget title,
    FItemVariant variant = .primary,
    FItemStyleDelta style = const .context(),
    bool? enabled,
    bool selected = false,
    String? semanticsLabel,
    bool autofocus = false,
    FocusNode? focusNode,
    ValueChanged<bool>? onFocusChange,
    ValueChanged<bool>? onHoverChange,
    FTappableVariantChangeCallback? onVariantChange,
    VoidCallback? onPress,
    VoidCallback? onLongPress,
    VoidCallback? onDoubleTap,
    VoidCallback? onSecondaryPress,
    VoidCallback? onSecondaryLongPress,
    Map<ShortcutActivator, Intent>? shortcuts,
    Map<Type, Action<Intent>>? actions,
    Widget? prefix,
    Widget? subtitle,
    Widget? details,
    Widget? suffix,
    Key? key,
  }) => .new(
    title: title,
    variant: variant,
    style: style,
    enabled: enabled,
    selected: selected,
    semanticsLabel: semanticsLabel,
    autofocus: autofocus,
    focusNode: focusNode,
    onFocusChange: onFocusChange,
    onHoverChange: onHoverChange,
    onVariantChange: onVariantChange,
    onPress: onPress,
    onLongPress: onLongPress,
    onDoubleTap: onDoubleTap,
    onSecondaryPress: onSecondaryPress,
    onSecondaryLongPress: onSecondaryLongPress,
    shortcuts: shortcuts,
    actions: actions,
    prefix: prefix,
    subtitle: subtitle,
    details: details,
    suffix: suffix,
    key: key,
  );

  /// {@macro forui.widgets.FTile.raw}
  ///
  /// This function is a shorthand for [FTile.raw].
  static FTile raw({
    required Widget child,
    FItemVariant variant = .primary,
    FItemStyleDelta style = const .context(),
    bool? enabled,
    bool selected = false,
    String? semanticsLabel,
    bool autofocus = false,
    FocusNode? focusNode,
    ValueChanged<bool>? onFocusChange,
    ValueChanged<bool>? onHoverChange,
    FTappableVariantChangeCallback? onVariantChange,
    VoidCallback? onPress,
    VoidCallback? onLongPress,
    VoidCallback? onDoubleTap,
    VoidCallback? onSecondaryPress,
    VoidCallback? onSecondaryLongPress,
    Map<ShortcutActivator, Intent>? shortcuts,
    Map<Type, Action<Intent>>? actions,
    Widget? prefix,
    Key? key,
  }) => .raw(
    variant: variant,
    style: style,
    enabled: enabled,
    selected: selected,
    semanticsLabel: semanticsLabel,
    autofocus: autofocus,
    focusNode: focusNode,
    onFocusChange: onFocusChange,
    onHoverChange: onHoverChange,
    onVariantChange: onVariantChange,
    onPress: onPress,
    onLongPress: onLongPress,
    onDoubleTap: onDoubleTap,
    onSecondaryPress: onSecondaryPress,
    onSecondaryLongPress: onSecondaryLongPress,
    shortcuts: shortcuts,
    actions: actions,
    prefix: prefix,
    key: key,
    child: child,
  );
}
