// Copyright 2025 The Flutter Authors.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:collection/collection.dart';
import 'package:json_annotation/json_annotation.dart';

import 'part.dart';

part 'message.g.dart';

/// Identifies the sender of a [Message].
enum Role {
  /// The message originated from the user (i.e., the A2A client).
  user,

  /// The message originated from the agent (i.e., the A2A server).
  agent,
}

/// Represents a single communication exchange within an A2A interaction.
///
/// Messages are the fundamental unit of communication, used for sending
/// instructions, prompts, data, and replies between a client and an agent.
/// A message consists of one or more [Part]s, allowing for rich content.
@JsonSerializable()
class Message {
  /// Specifies the sender of the message, either [Role.user] or [Role.agent].
  final Role role;

  /// A list of content [Part]s that make up the message body.
  ///
  /// A message can be composed of multiple parts of different types
  /// (e.g., text, files, structured data).
  final List<Part> parts;

  /// Optional metadata for extensions, as a map where the key is an
  /// extension-specific identifier.
  final Map<String, Object?>? metadata;

  /// Optional list of URIs for extensions that are relevant to this message.
  final List<String>? extensions;

  /// Optional list of other task IDs that this message references for
  /// additional context.
  final List<String>? referenceTaskIds;

  /// A unique identifier for this message, typically a UUID, generated by the
  /// sender.
  final String messageId;

  /// The ID of the task this message belongs to.
  ///
  /// This can be omitted for the initial message in a new task interaction.
  final String? taskId;

  /// An identifier used to group related messages and tasks, such as within
  /// a single conversation or session.
  final String? contextId;

  /// The type discriminator for this object, always 'message'.
  final String kind;

  /// Creates a [Message] instance.
  const Message({
    required this.role,
    required this.parts,
    this.metadata,
    this.extensions,
    this.referenceTaskIds,
    required this.messageId,
    this.taskId,
    this.contextId,
    this.kind = 'message',
  });

  /// Deserializes a [Message] instance from a JSON object.
  factory Message.fromJson(Map<String, Object?> json) =>
      _$MessageFromJson(json);

  /// Creates a JSON object from a [Message].
  Map<String, Object?> toJson() => _$MessageToJson(this);

  Message copyWith({
    Role? role,
    List<Part>? parts,
    Map<String, Object?>? metadata,
    List<String>? extensions,
    List<String>? referenceTaskIds,
    String? messageId,
    String? taskId,
    String? contextId,
    String? kind,
  }) {
    return Message(
      role: role ?? this.role,
      parts: parts ?? this.parts,
      metadata: metadata ?? this.metadata,
      extensions: extensions ?? this.extensions,
      referenceTaskIds: referenceTaskIds ?? this.referenceTaskIds,
      messageId: messageId ?? this.messageId,
      taskId: taskId ?? this.taskId,
      contextId: contextId ?? this.contextId,
      kind: kind ?? this.kind,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Message &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          const DeepCollectionEquality().equals(parts, other.parts) &&
          const DeepCollectionEquality().equals(metadata, other.metadata) &&
          const DeepCollectionEquality().equals(extensions, other.extensions) &&
          const DeepCollectionEquality().equals(
            referenceTaskIds,
            other.referenceTaskIds,
          ) &&
          messageId == other.messageId &&
          taskId == other.taskId &&
          contextId == other.contextId &&
          kind == other.kind;

  @override
  int get hashCode => Object.hash(
    role,
    const DeepCollectionEquality().hash(parts),
    const DeepCollectionEquality().hash(metadata),
    const DeepCollectionEquality().hash(extensions),
    const DeepCollectionEquality().hash(referenceTaskIds),
    messageId,
    taskId,
    contextId,
    kind,
  );

  @override
  String toString() =>
      '''Message(role: $role, parts: $parts, metadata: $metadata, extensions: $extensions, referenceTaskIds: $referenceTaskIds, messageId: $messageId, taskId: $taskId, contextId: $contextId, kind: $kind)''';
}
