// Copyright 2025 The Flutter Authors.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:collection/collection.dart';
import 'package:json_annotation/json_annotation.dart';
import '../../string_utils.dart';

import 'message.dart';
import 'part.dart';

part 'task.g.dart';

/// Represents a stateful operation or conversation between a client and an
/// agent.
///
/// A [Task] encapsulates the entire lifecycle of an interaction, including its
/// current status, history of messages, and any generated artifacts.
@JsonSerializable()
class Task {
  /// A unique identifier (e.g., UUID) for the task.
  ///
  /// This ID is typically generated by the server when a new task is created.
  final String id;

  /// A server-generated unique identifier (e.g., UUID) for grouping related
  /// tasks or interactions, forming a conversation context.
  final String contextId;

  /// The current status of the task, including its state and any associated
  /// message.
  final TaskStatus status;

  /// An optional list of [Message] objects representing the conversation
  /// history of the task.
  final List<Message>? history;

  /// An optional collection of [Artifact]s produced by the agent during the
  /// task's execution.
  final List<Artifact>? artifacts;

  /// Optional metadata for extensions, as a map where the key is an
  /// extension-specific identifier.
  final Map<String, Object?>? metadata;

  /// The timestamp of the last update to the task, in milliseconds since the
  /// Unix epoch.
  final int? lastUpdated;

  /// The type discriminator for this object, always 'task'.
  final String kind;

  /// Creates a [Task] instance.
  const Task({
    required this.id,
    required this.contextId,
    required this.status,
    this.history,
    this.artifacts,
    this.metadata,
    this.lastUpdated,
    this.kind = 'task',
  });

  /// Deserializes a [Task] instance from a JSON object.
  factory Task.fromJson(Map<String, Object?> json) => _$TaskFromJson(json);

  /// Creates a JSON object from a [Task].
  Map<String, Object?> toJson() => _$TaskToJson(this);

  Task copyWith({
    String? id,
    String? contextId,
    TaskStatus? status,
    List<Message>? history,
    List<Artifact>? artifacts,
    Map<String, Object?>? metadata,
    int? lastUpdated,
    String? kind,
  }) {
    return Task(
      id: id ?? this.id,
      contextId: contextId ?? this.contextId,
      status: status ?? this.status,
      history: history ?? this.history,
      artifacts: artifacts ?? this.artifacts,
      metadata: metadata ?? this.metadata,
      lastUpdated: lastUpdated ?? this.lastUpdated,
      kind: kind ?? this.kind,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Task &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          contextId == other.contextId &&
          status == other.status &&
          const DeepCollectionEquality().equals(history, other.history) &&
          const DeepCollectionEquality().equals(artifacts, other.artifacts) &&
          const DeepCollectionEquality().equals(metadata, other.metadata) &&
          lastUpdated == other.lastUpdated &&
          kind == other.kind;

  @override
  int get hashCode => Object.hash(
    id,
    contextId,
    status,
    const DeepCollectionEquality().hash(history),
    const DeepCollectionEquality().hash(artifacts),
    const DeepCollectionEquality().hash(metadata),
    lastUpdated,
    kind,
  );

  @override
  String toString() => buildToString('Task', {
    'id': id,
    'contextId': contextId,
    'status': status,
    'history': history,
    'artifacts': artifacts,
    'metadata': metadata,
    'lastUpdated': lastUpdated,
    'kind': kind,
  });
}

/// Represents the status of a [Task] at a specific point in time.
@JsonSerializable()
class TaskStatus {
  /// The current state in the task's lifecycle.
  final TaskState state;

  /// An optional, human-readable [Message] providing more details about the
  /// current status (e.g., an error message or a prompt for input).
  final Message? message;

  /// The timestamp when this status was recorded, in milliseconds since the
  /// Unix epoch.
  final String? timestamp;

  /// Creates a [TaskStatus] instance.
  const TaskStatus({required this.state, this.message, this.timestamp});

  /// Deserializes a [TaskStatus] instance from a JSON object.
  factory TaskStatus.fromJson(Map<String, Object?> json) =>
      _$TaskStatusFromJson(json);

  /// Creates a JSON object from a [TaskStatus].
  Map<String, Object?> toJson() => _$TaskStatusToJson(this);

  TaskStatus copyWith({TaskState? state, Message? message, String? timestamp}) {
    return TaskStatus(
      state: state ?? this.state,
      message: message ?? this.message,
      timestamp: timestamp ?? this.timestamp,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskStatus &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          message == other.message &&
          timestamp == other.timestamp;

  @override
  int get hashCode => Object.hash(state, message, timestamp);

  @override
  String toString() =>
      'TaskStatus(state: $state, message: $message, timestamp: $timestamp)';
}

/// Defines the possible lifecycle states of a [Task].
@JsonEnum(fieldRename: FieldRename.kebab)
enum TaskState {
  /// The task has been received by the server but not yet started.
  submitted,

  /// The agent is actively processing the task.
  working,

  /// The task is paused, awaiting further input from the client.
  inputRequired,

  /// The task has been successfully completed by the agent.
  completed,

  /// The task was canceled, typically by a client request.
  canceled,

  /// The task failed due to an error during execution.
  failed,

  /// The task was rejected by the agent before execution began (e.g., due to
  /// invalid parameters or permissions).
  rejected,

  /// The task cannot proceed without additional authentication or
  /// authorization.
  authRequired,

  /// The task is in an unknown or indeterminate state.
  unknown,
}

/// Represents a file, data structure, or other resource generated by an agent
/// during a [Task].
@JsonSerializable()
class Artifact {
  /// A unique identifier for this artifact within the scope of the task.
  final String artifactId;

  /// An optional, human-readable name for the artifact.
  final String? name;

  /// An optional, human-readable description of the artifact's content or
  /// purpose.
  final String? description;

  /// A list of [Part] objects that constitute the content of the artifact.
  final List<Part> parts;

  /// Optional metadata for extensions.
  final Map<String, Object?>? metadata;

  /// Optional list of URIs for extensions that are relevant to this artifact.
  final List<String>? extensions;

  /// Creates an [Artifact] instance.
  const Artifact({
    required this.artifactId,
    this.name,
    this.description,
    required this.parts,
    this.metadata,
    this.extensions,
  });

  /// Deserializes an [Artifact] instance from a JSON object.
  factory Artifact.fromJson(Map<String, Object?> json) =>
      _$ArtifactFromJson(json);

  /// Creates a JSON object from a [Artifact].
  Map<String, Object?> toJson() => _$ArtifactToJson(this);

  Artifact copyWith({
    String? artifactId,
    String? name,
    String? description,
    List<Part>? parts,
    Map<String, Object?>? metadata,
    List<String>? extensions,
  }) {
    return Artifact(
      artifactId: artifactId ?? this.artifactId,
      name: name ?? this.name,
      description: description ?? this.description,
      parts: parts ?? this.parts,
      metadata: metadata ?? this.metadata,
      extensions: extensions ?? this.extensions,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Artifact &&
          runtimeType == other.runtimeType &&
          artifactId == other.artifactId &&
          name == other.name &&
          description == other.description &&
          const DeepCollectionEquality().equals(parts, other.parts) &&
          const DeepCollectionEquality().equals(metadata, other.metadata) &&
          const DeepCollectionEquality().equals(extensions, other.extensions);

  @override
  int get hashCode => Object.hash(
    artifactId,
    name,
    description,
    const DeepCollectionEquality().hash(parts),
    const DeepCollectionEquality().hash(metadata),
    const DeepCollectionEquality().hash(extensions),
  );

  @override
  String toString() =>
      'Artifact(artifactId: $artifactId, name: $name, '
      'description: $description, parts: $parts, metadata: $metadata, '
      'extensions: $extensions)';
}
