// ignore_for_file: unnecessary_import
// {@snippet}

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'package:forui/forui.dart';

part 'colors.dart';
part 'typography.dart';
part 'style.dart';

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified function and pass it to [FTheme].
///
/// You can also generate styles to be used in the generated [FThemeData] using:
/// ```shell
/// dart forui style create [styles]
/// ```
///
/// See:
/// * https://forui.dev/docs/guides/customizing-themes for customizing themes.
/// * https://forui.dev/docs/guides/customizing-widget-styles for customizing individual widget styles.
FThemeData get neutralLight {
  // Change this to false to use the desktop variant of this theme.
  const touch = true;

  final colors = lightColors;

  final typography = _typography(colors: colors, touch: touch);

  final icons = FIcons(
    arrowLeft: FIcons.iconData(FLucideIcons.arrowLeft),
    calendar: FIcons.iconData(FLucideIcons.calendar),
    check: FIcons.iconData(FLucideIcons.check),
    chevronDown: FIcons.iconData(FLucideIcons.chevronDown),
    chevronLeft: FIcons.iconData(FLucideIcons.chevronLeft),
    chevronRight: FIcons.iconData(FLucideIcons.chevronRight),
    chevronUp: FIcons.iconData(FLucideIcons.chevronUp),
    chevronsUpDown: FIcons.iconData(FLucideIcons.chevronsUpDown),
    circleAlert: FIcons.iconData(FLucideIcons.circleAlert),
    clock4: FIcons.iconData(FLucideIcons.clock4),
    ellipsis: FIcons.iconData(FLucideIcons.ellipsis),
    eye: FIcons.iconData(FLucideIcons.eye),
    eyeClosed: FIcons.iconData(FLucideIcons.eyeClosed),
    gripHorizontal: FIcons.iconData(FLucideIcons.gripHorizontal),
    gripVertical: FIcons.iconData(FLucideIcons.gripVertical),
    loader: FIcons.iconData(FLucideIcons.loader),
    loaderCircle: FIcons.iconData(FLucideIcons.loaderCircle),
    loaderPinwheel: FIcons.iconData(FLucideIcons.loaderPinwheel),
    search: FIcons.iconData(FLucideIcons.search),
    userRound: FIcons.iconData(FLucideIcons.userRound),
    x: FIcons.iconData(FLucideIcons.x),
  );

  final style = _style(colors: colors, typography: typography, touch: touch);

  return FThemeData(colors: colors, typography: typography, icons: icons, style: style, touch: touch);
}

FThemeData get neutralDark {
  // Change this to false to use the desktop variant of this theme.
  const touch = true;

  final colors = darkColors;

  final typography = _typography(colors: colors, touch: touch);

  final icons = FIcons(
    arrowLeft: FIcons.iconData(FLucideIcons.arrowLeft),
    calendar: FIcons.iconData(FLucideIcons.calendar),
    check: FIcons.iconData(FLucideIcons.check),
    chevronDown: FIcons.iconData(FLucideIcons.chevronDown),
    chevronLeft: FIcons.iconData(FLucideIcons.chevronLeft),
    chevronRight: FIcons.iconData(FLucideIcons.chevronRight),
    chevronUp: FIcons.iconData(FLucideIcons.chevronUp),
    chevronsUpDown: FIcons.iconData(FLucideIcons.chevronsUpDown),
    circleAlert: FIcons.iconData(FLucideIcons.circleAlert),
    clock4: FIcons.iconData(FLucideIcons.clock4),
    ellipsis: FIcons.iconData(FLucideIcons.ellipsis),
    eye: FIcons.iconData(FLucideIcons.eye),
    eyeClosed: FIcons.iconData(FLucideIcons.eyeClosed),
    gripHorizontal: FIcons.iconData(FLucideIcons.gripHorizontal),
    gripVertical: FIcons.iconData(FLucideIcons.gripVertical),
    loader: FIcons.iconData(FLucideIcons.loader),
    loaderCircle: FIcons.iconData(FLucideIcons.loaderCircle),
    loaderPinwheel: FIcons.iconData(FLucideIcons.loaderPinwheel),
    search: FIcons.iconData(FLucideIcons.search),
    userRound: FIcons.iconData(FLucideIcons.userRound),
    x: FIcons.iconData(FLucideIcons.x),
  );

  final style = _style(colors: colors, typography: typography, touch: touch);

  return FThemeData(colors: colors, typography: typography, icons: icons, style: style, touch: touch);
}

// {@endsnippet}
