// {@snippet}
part of 'theme.dart';

/// Generated by Forui CLI.
///
/// Typography tokens and theme extensions for the generated theme.
FTypography _typography({
  required FColors colors,
  required bool touch,
  String fontFamily = FTypography.defaultFontFamily,
}) {
  assert(fontFamily.isNotEmpty, 'fontFamily ($fontFamily) should not be empty.');
  final color = colors.foreground;
  final font = fontFamily;
  if (touch) {
    return FTypography(
      fontFamily: fontFamily,
      xs3: TextStyle(color: color, fontFamily: font, fontSize: 10, height: 1, leadingDistribution: .even),
      xs2: TextStyle(color: color, fontFamily: font, fontSize: 12, height: 1, leadingDistribution: .even),
      xs: TextStyle(color: color, fontFamily: font, fontSize: 14, height: 1.25, leadingDistribution: .even),
      sm: TextStyle(color: color, fontFamily: font, fontSize: 16, height: 1.5, leadingDistribution: .even),
      md: TextStyle(color: color, fontFamily: font, fontSize: 18, height: 1.75, leadingDistribution: .even),
      lg: TextStyle(color: color, fontFamily: font, fontSize: 20, height: 1.75, leadingDistribution: .even),
      xl: TextStyle(color: color, fontFamily: font, fontSize: 22, height: 2, leadingDistribution: .even),
      xl2: TextStyle(color: color, fontFamily: font, fontSize: 30, height: 2.25, leadingDistribution: .even),
      xl3: TextStyle(color: color, fontFamily: font, fontSize: 36, height: 2.5, leadingDistribution: .even),
      xl4: TextStyle(color: color, fontFamily: font, fontSize: 48, height: 1, leadingDistribution: .even),
      xl5: TextStyle(color: color, fontFamily: font, fontSize: 60, height: 1, leadingDistribution: .even),
      xl6: TextStyle(color: color, fontFamily: font, fontSize: 72, height: 1, leadingDistribution: .even),
      xl7: TextStyle(color: color, fontFamily: font, fontSize: 96, height: 1, leadingDistribution: .even),
      xl8: TextStyle(color: color, fontFamily: font, fontSize: 108, height: 1, leadingDistribution: .even),
      extensions: const [AppTypography()],
    );
  } else {
    return FTypography(
      fontFamily: fontFamily,
      xs3: TextStyle(color: color, fontFamily: font, fontSize: 8, height: 1, leadingDistribution: .even),
      xs2: TextStyle(color: color, fontFamily: font, fontSize: 10, height: 1, leadingDistribution: .even),
      xs: TextStyle(color: color, fontFamily: font, fontSize: 12, height: 1, leadingDistribution: .even),
      sm: TextStyle(color: color, fontFamily: font, fontSize: 14, height: 1.25, leadingDistribution: .even),
      md: TextStyle(color: color, fontFamily: font, fontSize: 16, height: 1.5, leadingDistribution: .even),
      lg: TextStyle(color: color, fontFamily: font, fontSize: 18, height: 1.75, leadingDistribution: .even),
      xl: TextStyle(color: color, fontFamily: font, fontSize: 20, height: 1.75, leadingDistribution: .even),
      xl2: TextStyle(color: color, fontFamily: font, fontSize: 22, height: 2, leadingDistribution: .even),
      xl3: TextStyle(color: color, fontFamily: font, fontSize: 30, height: 2.25, leadingDistribution: .even),
      xl4: TextStyle(color: color, fontFamily: font, fontSize: 36, height: 2.5, leadingDistribution: .even),
      xl5: TextStyle(color: color, fontFamily: font, fontSize: 48, height: 1, leadingDistribution: .even),
      xl6: TextStyle(color: color, fontFamily: font, fontSize: 60, height: 1, leadingDistribution: .even),
      xl7: TextStyle(color: color, fontFamily: font, fontSize: 72, height: 1, leadingDistribution: .even),
      xl8: TextStyle(color: color, fontFamily: font, fontSize: 96, height: 1, leadingDistribution: .even),
      extensions: const [AppTypography()],
    );
  }
}

/// Provides convenient access to theme extensions on [FTypography].
///
/// ```dart
/// final display = context.theme.typography.app.display; ✅
///
/// // Alternatively, you can create a getter to access extension fields directly.
/// final display = context.theme.typography.display; ✅
///
/// final display = context.theme.typography.extension<AppTypography>().display; ❌
/// ```
extension FTypographyExtensions on FTypography {
  AppTypography get app => extension<AppTypography>();
}

/// Custom typography tokens unique to your app.
///
/// Add your fields below, then implement [copyWith], [lerp], [scale], [==], and [hashCode].
/// See [FTypographyExtension].
class AppTypography extends FTypographyExtension<AppTypography> {
  // TODO: add your typography fields here:
  // final TextStyle display;

  const AppTypography();

  @override
  AppTypography copyWith() => const AppTypography();

  @override
  AppTypography lerp(covariant AppTypography? other, double t) {
    if (other == null) {
      return this;
    }
    return const AppTypography();
  }

  @override
  AppTypography scale({double sizeScalar = 1.0}) => this;

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is AppTypography && runtimeType == other.runtimeType;

  @override
  int get hashCode => runtimeType.hashCode;
}

// {@endsnippet}
