name: _
environment:
  sdk: ">=3.12.0-0 <4.0.0"
  flutter: ">=3.44.0-0"
workspace:
  - demo
  - docs_snippets
  - forui
  - forui_assets
  - forui_hooks
  - forui_internal_gen

dev_dependencies:
  flint: ^2.15.0
