import 'package:flutter/gestures.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/widgets.dart';

import 'package:forui/forui.dart';

/// A marker interface which denotes that mixed-in widgets is an item.
mixin FItemMixin on Widget {
  /// {@macro forui.widgets.FItem.new}
  ///
  /// This function is a shorthand for [FItem.new].
  static FItem item({
    required Widget title,
    FItemVariant variant = .primary,
    FItemStyleDelta style = const .context(),
    bool? enabled,
    bool selected = false,
    String? semanticsLabel,
    bool autofocus = false,
    FocusNode? focusNode,
    ValueChanged<bool>? onFocusChange,
    ValueChanged<bool>? onHoverChange,
    FTappableVariantChangeCallback? onVariantChange,
    VoidCallback? onPress,
    VoidCallback? onLongPress,
    VoidCallback? onDoubleTap,
    VoidCallback? onSecondaryPress,
    VoidCallback? onSecondaryLongPress,
    Map<ShortcutActivator, Intent>? shortcuts,
    Map<Type, Action<Intent>>? actions,
    Widget? prefix,
    Widget? subtitle,
    Widget? details,
    Widget? suffix,
    Key? key,
  }) => .new(
    title: title,
    variant: variant,
    style: style,
    enabled: enabled,
    selected: selected,
    semanticsLabel: semanticsLabel,
    autofocus: autofocus,
    focusNode: focusNode,
    onFocusChange: onFocusChange,
    onHoverChange: onHoverChange,
    onVariantChange: onVariantChange,
    onPress: onPress,
    onLongPress: onLongPress,
    onDoubleTap: onDoubleTap,
    onSecondaryPress: onSecondaryPress,
    onSecondaryLongPress: onSecondaryLongPress,
    shortcuts: shortcuts,
    actions: actions,
    prefix: prefix,
    subtitle: subtitle,
    details: details,
    suffix: suffix,
    key: key,
  );

  /// Creates a [FSubmenuItem].
  ///
  /// This function is a shorthand for [FSubmenuItem.new].
  static FSubmenuItem submenu({
    required Widget title,
    required List<FItemGroupMixin> submenu,
    FPopoverControl control = const .managed(),
    FItemVariant variant = .primary,
    FItemStyleDelta style = const .context(),
    bool? enabled,
    String? semanticsLabel,
    bool autofocus = false,
    FocusNode? focusNode,
    ValueChanged<bool>? onFocusChange,
    ValueChanged<bool>? onHoverChange,
    FTappableVariantChangeCallback? onVariantChange,
    VoidCallback? onLongPress,
    VoidCallback? onDoubleTap,
    VoidCallback? onSecondaryPress,
    VoidCallback? onSecondaryLongPress,
    Map<ShortcutActivator, Intent>? shortcuts,
    Map<Type, Action<Intent>>? actions,
    Widget? prefix,
    Widget? subtitle,
    Widget? suffix,
    FPopoverMenuStyleDelta menuStyle = const .context(),
    AlignmentGeometry? menuAnchor,
    AlignmentGeometry? itemAnchor,
    ScrollController? submenuScrollController,
    ScrollCacheExtent? submenuScrollCacheExtent,
    bool? submenuIntrinsicWidth,
    DragStartBehavior submenuDragStartBehavior = .start,
    FPortalSpacing submenuSpacing = const .spacing(2),
    FPortalOverflow submenuOverflow = .flip,
    Offset submenuOffset = .zero,
    FPopoverHideRegion submenuHideRegion = .excludeChild,
    String? submenuSemanticsLabel,
    bool submenuUseViewPadding = true,
    bool submenuUseViewInsets = true,
    bool? submenuAutofocus,
    FocusScopeNode? submenuFocusNode,
    ValueChanged<bool>? submenuOnFocusChange,
    TraversalEdgeBehavior? submenuTraversalEdgeBehavior,
    double submenuMaxHeight = .infinity,
    FItemDivider submenuDivider = .full,
    Key? key,
  }) => .new(
    title: title,
    submenu: submenu,
    control: control,
    variant: variant,
    style: style,
    enabled: enabled,
    semanticsLabel: semanticsLabel,
    autofocus: autofocus,
    focusNode: focusNode,
    onFocusChange: onFocusChange,
    onHoverChange: onHoverChange,
    onVariantChange: onVariantChange,
    onLongPress: onLongPress,
    onDoubleTap: onDoubleTap,
    onSecondaryPress: onSecondaryPress,
    onSecondaryLongPress: onSecondaryLongPress,
    shortcuts: shortcuts,
    actions: actions,
    prefix: prefix,
    subtitle: subtitle,
    suffix: suffix,
    submenuStyle: menuStyle,
    submenuAnchor: menuAnchor,
    itemAnchor: itemAnchor,
    submenuScrollController: submenuScrollController,
    submenuScrollCacheExtent: submenuScrollCacheExtent,
    submenuIntrinsicWidth: submenuIntrinsicWidth,
    submenuDragStartBehavior: submenuDragStartBehavior,
    submenuSpacing: submenuSpacing,
    submenuOverflow: submenuOverflow,
    submenuOffset: submenuOffset,
    submenuHideRegion: submenuHideRegion,
    submenuSemanticsLabel: submenuSemanticsLabel,
    submenuUseViewPadding: submenuUseViewPadding,
    submenuUseViewInsets: submenuUseViewInsets,
    submenuAutofocus: submenuAutofocus,
    submenuFocusNode: submenuFocusNode,
    submenuOnFocusChange: submenuOnFocusChange,
    submenuTraversalEdgeBehavior: submenuTraversalEdgeBehavior,
    submenuMaxHeight: submenuMaxHeight,
    submenuDivider: submenuDivider,
    key: key,
  );

  /// {@macro forui.widgets.FItem.raw}
  ///
  /// This function is a shorthand for [FItem.raw].
  static FItem raw({
    required Widget child,
    FItemVariant variant = .primary,
    FItemStyleDelta style = const .context(),
    bool? enabled,
    bool selected = false,
    String? semanticsLabel,
    bool autofocus = false,
    FocusNode? focusNode,
    ValueChanged<bool>? onFocusChange,
    ValueChanged<bool>? onHoverChange,
    FTappableVariantChangeCallback? onVariantChange,
    VoidCallback? onPress,
    VoidCallback? onLongPress,
    VoidCallback? onDoubleTap,
    VoidCallback? onSecondaryPress,
    VoidCallback? onSecondaryLongPress,
    Map<ShortcutActivator, Intent>? shortcuts,
    Map<Type, Action<Intent>>? actions,
    Widget? prefix,
    Key? key,
  }) => .raw(
    variant: variant,
    style: style,
    enabled: enabled,
    selected: selected,
    semanticsLabel: semanticsLabel,
    autofocus: autofocus,
    focusNode: focusNode,
    onFocusChange: onFocusChange,
    onHoverChange: onHoverChange,
    onVariantChange: onVariantChange,
    onPress: onPress,
    onLongPress: onLongPress,
    onDoubleTap: onDoubleTap,
    onSecondaryPress: onSecondaryPress,
    onSecondaryLongPress: onSecondaryLongPress,
    shortcuts: shortcuts,
    actions: actions,
    prefix: prefix,
    key: key,
    child: child,
  );
}
